# Generated by Django 4.2.3 on 2023-07-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('lift_id', models.IntegerField(null=True)),
                ('archived_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('lift_number', models.AutoField(primary_key=True, serialize=False)),
                ('is_operational', models.BooleanField(default=True)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('current_floor', models.IntegerField(default=0)),
                ('moving_up', models.SmallIntegerField(default=0)),
                ('is_upward', models.SmallIntegerField(default=0)),
                ('is_door_close_open', models.BooleanField(default=0)),
                ('requests', models.ManyToManyField(related_name='elevators', to='elevator.floorrequest')),
            ],
        ),
    ]
